"""autogenerated by genmsg_py from MotorConfig.msg. Do not edit."""
import roslib.message
import struct


class MotorConfig(roslib.message.Message):
  _md5sum = "0d2bdd7715a3b4f9c71fa4aa5bd10a18"
  _type = "custom_msg/MotorConfig"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int8 front
int8 back
int8 front_right
int8 back_right
int8 front_left
int8 back_left

"""
  __slots__ = ['front','back','front_right','back_right','front_left','back_left']
  _slot_types = ['int8','int8','int8','int8','int8','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       front,back,front_right,back_right,front_left,back_left
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(MotorConfig, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.front is None:
        self.front = 0
      if self.back is None:
        self.back = 0
      if self.front_right is None:
        self.front_right = 0
      if self.back_right is None:
        self.back_right = 0
      if self.front_left is None:
        self.front_left = 0
      if self.back_left is None:
        self.back_left = 0
    else:
      self.front = 0
      self.back = 0
      self.front_right = 0
      self.back_right = 0
      self.front_left = 0
      self.back_left = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_6b.pack(_x.front, _x.back, _x.front_right, _x.back_right, _x.front_left, _x.back_left))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.front, _x.back, _x.front_right, _x.back_right, _x.front_left, _x.back_left,) = _struct_6b.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_6b.pack(_x.front, _x.back, _x.front_right, _x.back_right, _x.front_left, _x.back_left))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.front, _x.back, _x.front_right, _x.back_right, _x.front_left, _x.back_left,) = _struct_6b.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_6b = struct.Struct("<6b")
