"""autogenerated by genmsg_py from SonarData.msg. Do not edit."""
import roslib.message
import struct

import std_msgs.msg

class SonarData(roslib.message.Message):
  _md5sum = "309be5194d79c53268060b45eeee6151"
  _type = "custom_msg/SonarData"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 bearing
float32 threshold
float32 contrast
float32 min_distance
float32 max_distance
float32 resolution
std_msgs/Int32MultiArray bins

================================================================================
MSG: std_msgs/Int32MultiArray
# Please look at the MultiArrayLayout message definition for
# documentation on all multiarrays.

MultiArrayLayout  layout        # specification of data layout
int32[]           data          # array of data


================================================================================
MSG: std_msgs/MultiArrayLayout
# The multiarray declares a generic multi-dimensional array of a
# particular data type.  Dimensions are ordered from outer most
# to inner most.

MultiArrayDimension[] dim # Array of dimension properties
uint32 data_offset        # padding bytes at front of data

# Accessors should ALWAYS be written in terms of dimension stride
# and specified outer-most dimension first.
# 
# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]
#
# A standard, 3-channel 640x480 image with interleaved color channels
# would be specified as:
#
# dim[0].label  = "height"
# dim[0].size   = 480
# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)
# dim[1].label  = "width"
# dim[1].size   = 640
# dim[1].stride = 3*640 = 1920
# dim[2].label  = "channel"
# dim[2].size   = 3
# dim[2].stride = 3
#
# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.
================================================================================
MSG: std_msgs/MultiArrayDimension
string label   # label of given dimension
uint32 size    # size of given dimension (in type units)
uint32 stride  # stride of given dimension
"""
  __slots__ = ['bearing','threshold','contrast','min_distance','max_distance','resolution','bins']
  _slot_types = ['float32','float32','float32','float32','float32','float32','std_msgs/Int32MultiArray']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       bearing,threshold,contrast,min_distance,max_distance,resolution,bins
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(SonarData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.bearing is None:
        self.bearing = 0.
      if self.threshold is None:
        self.threshold = 0.
      if self.contrast is None:
        self.contrast = 0.
      if self.min_distance is None:
        self.min_distance = 0.
      if self.max_distance is None:
        self.max_distance = 0.
      if self.resolution is None:
        self.resolution = 0.
      if self.bins is None:
        self.bins = std_msgs.msg.Int32MultiArray()
    else:
      self.bearing = 0.
      self.threshold = 0.
      self.contrast = 0.
      self.min_distance = 0.
      self.max_distance = 0.
      self.resolution = 0.
      self.bins = std_msgs.msg.Int32MultiArray()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_6f.pack(_x.bearing, _x.threshold, _x.contrast, _x.min_distance, _x.max_distance, _x.resolution))
      length = len(self.bins.layout.dim)
      buff.write(_struct_I.pack(length))
      for val1 in self.bins.layout.dim:
        _x = val1.label
        length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_struct_2I.pack(_x.size, _x.stride))
      buff.write(_struct_I.pack(self.bins.layout.data_offset))
      length = len(self.bins.data)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.pack(pattern, *self.bins.data))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.bins is None:
        self.bins = std_msgs.msg.Int32MultiArray()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.bearing, _x.threshold, _x.contrast, _x.min_distance, _x.max_distance, _x.resolution,) = _struct_6f.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.bins.layout.dim = []
      for i in range(0, length):
        val1 = std_msgs.msg.MultiArrayDimension()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        val1.label = str[start:end]
        _x = val1
        start = end
        end += 8
        (_x.size, _x.stride,) = _struct_2I.unpack(str[start:end])
        self.bins.layout.dim.append(val1)
      start = end
      end += 4
      (self.bins.layout.data_offset,) = _struct_I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      end += struct.calcsize(pattern)
      self.bins.data = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_6f.pack(_x.bearing, _x.threshold, _x.contrast, _x.min_distance, _x.max_distance, _x.resolution))
      length = len(self.bins.layout.dim)
      buff.write(_struct_I.pack(length))
      for val1 in self.bins.layout.dim:
        _x = val1.label
        length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_struct_2I.pack(_x.size, _x.stride))
      buff.write(_struct_I.pack(self.bins.layout.data_offset))
      length = len(self.bins.data)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.bins.data.tostring())
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.bins is None:
        self.bins = std_msgs.msg.Int32MultiArray()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.bearing, _x.threshold, _x.contrast, _x.min_distance, _x.max_distance, _x.resolution,) = _struct_6f.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.bins.layout.dim = []
      for i in range(0, length):
        val1 = std_msgs.msg.MultiArrayDimension()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        val1.label = str[start:end]
        _x = val1
        start = end
        end += 8
        (_x.size, _x.stride,) = _struct_2I.unpack(str[start:end])
        self.bins.layout.dim.append(val1)
      start = end
      end += 4
      (self.bins.layout.data_offset,) = _struct_I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      end += struct.calcsize(pattern)
      self.bins.data = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_2I = struct.Struct("<2I")
_struct_6f = struct.Struct("<6f")
