"""autogenerated by genmsg_py from TargetVector.msg. Do not edit."""
import roslib.message
import struct


class TargetVector(roslib.message.Message):
  _md5sum = "c8a135bba33cf1fda99a3f5ca1bc439d"
  _type = "custom_msg/TargetVector"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 vector_x
float32 vector_y
float32 vector_z
float32 vector_yaw
float32 vector_pitch
float32 vector_roll


"""
  __slots__ = ['vector_x','vector_y','vector_z','vector_yaw','vector_pitch','vector_roll']
  _slot_types = ['float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       vector_x,vector_y,vector_z,vector_yaw,vector_pitch,vector_roll
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(TargetVector, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.vector_x is None:
        self.vector_x = 0.
      if self.vector_y is None:
        self.vector_y = 0.
      if self.vector_z is None:
        self.vector_z = 0.
      if self.vector_yaw is None:
        self.vector_yaw = 0.
      if self.vector_pitch is None:
        self.vector_pitch = 0.
      if self.vector_roll is None:
        self.vector_roll = 0.
    else:
      self.vector_x = 0.
      self.vector_y = 0.
      self.vector_z = 0.
      self.vector_yaw = 0.
      self.vector_pitch = 0.
      self.vector_roll = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_6f.pack(_x.vector_x, _x.vector_y, _x.vector_z, _x.vector_yaw, _x.vector_pitch, _x.vector_roll))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.vector_x, _x.vector_y, _x.vector_z, _x.vector_yaw, _x.vector_pitch, _x.vector_roll,) = _struct_6f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_6f.pack(_x.vector_x, _x.vector_y, _x.vector_z, _x.vector_yaw, _x.vector_pitch, _x.vector_roll))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.vector_x, _x.vector_y, _x.vector_z, _x.vector_yaw, _x.vector_pitch, _x.vector_roll,) = _struct_6f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_6f = struct.Struct("<6f")
